package org.sicdlab.microlecture.common.bean;

// Generated 2013-9-27 23:42:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name = "grade", catalog = "supper_microlecture")
public class Grade implements java.io.Serializable {

	private String gradeId;
	private User user;
	private String gradeObject;
	private Integer mark;

	public Grade() {
	}

	public Grade(String gradeId) {
		this.gradeId = gradeId;
	}

	public Grade(String gradeId, User user, String gradeObject, Integer mark) {
		this.gradeId = gradeId;
		this.user = user;
		this.gradeObject = gradeObject;
		this.mark = mark;
	}

	@Id
	@Column(name = "GRADE_ID", unique = true, nullable = false, length = 32)
	public String getGradeId() {
		return this.gradeId;
	}

	public void setGradeId(String gradeId) {
		this.gradeId = gradeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "GRADE_OBJECT", length = 32)
	public String getGradeObject() {
		return this.gradeObject;
	}

	public void setGradeObject(String gradeObject) {
		this.gradeObject = gradeObject;
	}

	@Column(name = "MARK")
	public Integer getMark() {
		return this.mark;
	}

	public void setMark(Integer mark) {
		this.mark = mark;
	}

}
