package org.sicdlab.microlecture.common.bean;

// Generated 2013-9-27 23:42:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WebInfo generated by hbm2java
 */
@Entity
@Table(name = "web_info", catalog = "supper_microlecture")
public class WebInfo implements java.io.Serializable {

	private String webInfoId;
	private String webInfoType;
	private String webInfoTitle;
	private String webInfoContent;

	public WebInfo() {
	}

	public WebInfo(String webInfoId) {
		this.webInfoId = webInfoId;
	}

	public WebInfo(String webInfoId, String webInfoType, String webInfoTitle,
			String webInfoContent) {
		this.webInfoId = webInfoId;
		this.webInfoType = webInfoType;
		this.webInfoTitle = webInfoTitle;
		this.webInfoContent = webInfoContent;
	}

	@Id
	@Column(name = "WEB_INFO_ID", unique = true, nullable = false, length = 32)
	public String getWebInfoId() {
		return this.webInfoId;
	}

	public void setWebInfoId(String webInfoId) {
		this.webInfoId = webInfoId;
	}

	@Column(name = "WEB_INFO_TYPE", length = 50)
	public String getWebInfoType() {
		return this.webInfoType;
	}

	public void setWebInfoType(String webInfoType) {
		this.webInfoType = webInfoType;
	}

	@Column(name = "WEB_INFO_TITLE", length = 50)
	public String getWebInfoTitle() {
		return this.webInfoTitle;
	}

	public void setWebInfoTitle(String webInfoTitle) {
		this.webInfoTitle = webInfoTitle;
	}

	@Column(name = "WEB_INFO_CONTENT", length = 65535)
	public String getWebInfoContent() {
		return this.webInfoContent;
	}

	public void setWebInfoContent(String webInfoContent) {
		this.webInfoContent = webInfoContent;
	}

}
