package org.sicdlab.microlecture.common.bean;

// Generated 2013-9-27 23:42:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Help generated by hbm2java
 */
@Entity
@Table(name = "help", catalog = "supper_microlecture")
public class Help implements java.io.Serializable {

	private String helpId;
	private String helpType;
	private String helpTitle;
	private String helpContent;

	public Help() {
	}

	public Help(String helpId) {
		this.helpId = helpId;
	}

	public Help(String helpId, String helpType, String helpTitle,
			String helpContent) {
		this.helpId = helpId;
		this.helpType = helpType;
		this.helpTitle = helpTitle;
		this.helpContent = helpContent;
	}

	@Id
	@Column(name = "HELP_ID", unique = true, nullable = false, length = 32)
	public String getHelpId() {
		return this.helpId;
	}

	public void setHelpId(String helpId) {
		this.helpId = helpId;
	}

	@Column(name = "HELP_TYPE", length = 50)
	public String getHelpType() {
		return this.helpType;
	}

	public void setHelpType(String helpType) {
		this.helpType = helpType;
	}

	@Column(name = "HELP_TITLE", length = 50)
	public String getHelpTitle() {
		return this.helpTitle;
	}

	public void setHelpTitle(String helpTitle) {
		this.helpTitle = helpTitle;
	}

	@Column(name = "HELP_CONTENT", length = 65535)
	public String getHelpContent() {
		return this.helpContent;
	}

	public void setHelpContent(String helpContent) {
		this.helpContent = helpContent;
	}

}
