package org.sicdlab.microlecture.common.bean;

// Generated 2013-9-27 23:42:58 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Goods generated by hbm2java
 */
@Entity
@Table(name = "goods", catalog = "supper_microlecture")
public class Goods implements java.io.Serializable {

	private String goodsId;
	private User userByCustomerId;
	private User userBySallerId;
	private String goodsObject;
	private String goodsIntro;
	private Integer price;
	private Integer number;
	private Date putawayDate;
	private String type;

	public Goods() {
	}

	public Goods(String goodsId) {
		this.goodsId = goodsId;
	}

	public Goods(String goodsId, User userByCustomerId, User userBySallerId,
			String goodsObject, String goodsIntro, Integer price,
			Integer number, Date putawayDate, String type) {
		this.goodsId = goodsId;
		this.userByCustomerId = userByCustomerId;
		this.userBySallerId = userBySallerId;
		this.goodsObject = goodsObject;
		this.goodsIntro = goodsIntro;
		this.price = price;
		this.number = number;
		this.putawayDate = putawayDate;
		this.type = type;
	}

	@Id
	@Column(name = "GOODS_ID", unique = true, nullable = false, length = 32)
	public String getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ID")
	public User getUserByCustomerId() {
		return this.userByCustomerId;
	}

	public void setUserByCustomerId(User userByCustomerId) {
		this.userByCustomerId = userByCustomerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SALLER_ID")
	public User getUserBySallerId() {
		return this.userBySallerId;
	}

	public void setUserBySallerId(User userBySallerId) {
		this.userBySallerId = userBySallerId;
	}

	@Column(name = "GOODS_OBJECT", length = 32)
	public String getGoodsObject() {
		return this.goodsObject;
	}

	public void setGoodsObject(String goodsObject) {
		this.goodsObject = goodsObject;
	}

	@Column(name = "GOODS_INTRO", length = 200)
	public String getGoodsIntro() {
		return this.goodsIntro;
	}

	public void setGoodsIntro(String goodsIntro) {
		this.goodsIntro = goodsIntro;
	}

	@Column(name = "PRICE")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Column(name = "NUMBER")
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PUTAWAY_DATE", length = 19)
	public Date getPutawayDate() {
		return this.putawayDate;
	}

	public void setPutawayDate(Date putawayDate) {
		this.putawayDate = putawayDate;
	}

	@Column(name = "TYPE", length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
