package org.sicdlab.microlecture.common.bean;

// Generated 2013-9-27 23:42:58 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question", catalog = "supper_microlecture")
public class Question implements java.io.Serializable {

	private String questionId;
	private String queestionContent;
	private String questionType;
	private String questionLv;
	private Set<Answer> answers = new HashSet<Answer>(0);

	public Question() {
	}

	public Question(String questionId) {
		this.questionId = questionId;
	}

	public Question(String questionId, String queestionContent,
			String questionType, String questionLv, Set<Answer> answers) {
		this.questionId = questionId;
		this.queestionContent = queestionContent;
		this.questionType = questionType;
		this.questionLv = questionLv;
		this.answers = answers;
	}

	@Id
	@Column(name = "QUESTION_ID", unique = true, nullable = false, length = 32)
	public String getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(String questionId) {
		this.questionId = questionId;
	}

	@Column(name = "QUEESTION_CONTENT", length = 200)
	public String getQueestionContent() {
		return this.queestionContent;
	}

	public void setQueestionContent(String queestionContent) {
		this.queestionContent = queestionContent;
	}

	@Column(name = "QUESTION_TYPE", length = 50)
	public String getQuestionType() {
		return this.questionType;
	}

	public void setQuestionType(String questionType) {
		this.questionType = questionType;
	}

	@Column(name = "QUESTION_LV", length = 50)
	public String getQuestionLv() {
		return this.questionLv;
	}

	public void setQuestionLv(String questionLv) {
		this.questionLv = questionLv;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "question")
	public Set<Answer> getAnswers() {
		return this.answers;
	}

	public void setAnswers(Set<Answer> answers) {
		this.answers = answers;
	}

}
