package org.sicdlab.microlecture.common.bean;

// Generated 2013-9-27 23:42:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Answer generated by hbm2java
 */
@Entity
@Table(name = "answer", catalog = "supper_microlecture")
public class Answer implements java.io.Serializable {

	private String answerId;
	private Question question;
	private String answerContent;
	private Integer answerScore;

	public Answer() {
	}

	public Answer(String answerId) {
		this.answerId = answerId;
	}

	public Answer(String answerId, Question question, String answerContent,
			Integer answerScore) {
		this.answerId = answerId;
		this.question = question;
		this.answerContent = answerContent;
		this.answerScore = answerScore;
	}

	@Id
	@Column(name = "ANSWER_ID", unique = true, nullable = false, length = 32)
	public String getAnswerId() {
		return this.answerId;
	}

	public void setAnswerId(String answerId) {
		this.answerId = answerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUESTION_ID")
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name = "ANSWER_CONTENT", length = 200)
	public String getAnswerContent() {
		return this.answerContent;
	}

	public void setAnswerContent(String answerContent) {
		this.answerContent = answerContent;
	}

	@Column(name = "ANSWER_SCORE")
	public Integer getAnswerScore() {
		return this.answerScore;
	}

	public void setAnswerScore(Integer answerScore) {
		this.answerScore = answerScore;
	}

}
